# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

# Platform.
platform: x64

clone_folder: c:\gopath\src\github.com\minio\minio

# environment variables
environment:
  GOPATH: c:\gopath
  GO15VENDOREXPERIMENT: 1

# scripts that run after cloning repository
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go test -race github.com/minio/minio/cmd...
  - go test -race github.com/minio/minio/pkg...
  - go test -coverprofile=coverage.txt -covermode=atomic
  - go run buildscripts/gen-ldflags.go > temp.txt
  - set /p BUILD_LDFLAGS=<temp.txt
  - go build -ldflags="%BUILD_LDFLAGS%" -o %GOPATH%\bin\minio.exe

after_test:
  - bash <(curl -s https://codecov.io/bash)

# to disable automatic tests
test: off

# to disable deployment
deploy: off
